apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}
  namespace: ${namespace}
data:
%{ for filename, content in migrations ~}
  "${filename}": |
%{ for line in split("\n", content) ~}
    ${line}
%{ endfor ~}
%{ endfor ~}
